name: output event details using issues
on: [issues]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: output event details
        run: |
          echo "event name: ${{toJson(github.event)}}"