name: run-node
on: [push]
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: check code
              uses: actions/checkout@v2
            - name: run test
              run: |
                npm install
                npm run lint -- --fix
                npm run build
                npm run test
          
